package com.example.taskmanager.dto;

/*
 * UserResponseDto
 * ----------------
 * This DTO represents the data that the SERVER sends back to the client.
 *
 * IMPORTANT:
 * - Contains id (generated by DB)
 * - Only safe fields are exposed
 * - No internal DB details
 */

public class UserResponseDto {

    private Long id;
    private String name;
    private String email;

    // Constructor used to create response object
    public UserResponseDto(Long id, String name, String email) {
        this.id = id;
        this.name = name;
        this.email = email;
    }

    // Getters only (no setters needed for response)
    public Long getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public String getEmail() {
        return email;
    }
}
